language: java
notifications:
  hipchat:
    rooms:
      secure: G2AXNM0brrnGqQTgqTRjE1gfVME8ErQWHviCgVDYob2BUes9E+DXhwZAYxaZ5g30iMrVE4UXQxEHBFnVpGTSaO1/KkhgajQKJ4Jm3CKIWMvn586s+JkRjEBv3Db3DU05goqx2bGW1mZufSXr7TpjkskmmdDiAzoSnXUIhYVipugNdTPSDj/m7/Gv1FOxOC7DnZ+YcAoLiHxFPiDsyK8ZLbbYHtDXUfNVQjthtuIUUIYySIFGHlx3N4yhSksbo7ZXQLGjBcTPwJ1cRtN67iM0hoAP7aoSfnWPKGFhhRfWPIP6/p3cNzOkopyNkqo+u2SyyvZwyTNH+aEkhAgHccQCcYqelhKiQIDWQTLff+wRI8F48EhwWfBGQ0qWviGc9qtVLcJLuWZZoAQ4oEYImPSuTcROCQHy+XeM0hJ4Yh3eM6Vv0hjVLorqPy+JnZLmuS2PgZ9pk41W+XnoLKp8IvTk7dHpMGI0JAqLszToarlbysrD08voUiacSnCJPNEN/kGiPdtlXQXtQItvv0hw1Ne0sTmWNFxTN7563jWTLbqkZeeeCmelYqjcCYvb0hzUiVheeNrh2eUm/82pzoYNxGTY78GQCbpSk86jPtO9T96+2hT/Hc4e11wqgJR8BezszTNY/dQ1oNdi9F8Nn3L8/uoifFs+DntSTnLdQxIgZp1eQMw=
deploy:
  provider: releases
  api_key:
    secure: N5Nio6JYXDVYhp5lcBoFrU6J5GlLmb1L8pi54HG2ErL7Lo6XE0GR9RmfNfWvTFNAHKnvcJJfT4YdrP3mcfGrsw0o1jZNfrCoKg5PmwsZBR0gxjlcUdLO88LTpfYc0wusoFiAFFMADIRH1i/x5buBPKvAsfW74GmX9Rr9yzYq+Tm2yAoJfs4sRMHOwKX5D2cVkIy6FT5WbCnLYr/3Te8cEsY73uMGuQAxr88SgLEGy/p46p9BlJHfpHvCVqmDPi3D2FG3Laffr9KGhV0gzUNcZOZp+1nCK67fgvLZhVaEOslYs+68JfYeqixPpqgzkMYYXFrcz3U/zIp8VoxmJKCdSDcGnk2zdeNzQmqVbjRyH8ZmGLQnetKGgODb7THjBuSXdtAziRPVj3uaiz3zCTHhPkfXbVvz/9LNPITYu4LEGT9QYt/2Sr0efl1d1T4gXagp3ugvu7geg3eUDn908+BbXiuiv7ZjwiX1HdOoGk3b4CbezXbnquNLC24I5nN9YcWkM2B0aE2bca20LBP7GrKDago1/Pq85qBVFaSeX4bZr8GcGxVv4uFPHW+sf8F2JgSyn2A052XLody79Rzmt+7TH8B/cuuEEnPWQsHIJiU/Rfgoe+XnQaTTXwc+IGlVfieW2Jjzm2IeuGEvUlgC/HwAUwdlcKToq9itIiIBeNmvxiI=
  file: build/libs/xltv-rubocop-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xltv-rubocop-plugin
