language: java
notifications:
  slack:
    secure: iLt8T9uWe76xMCY23JVVrgPsnH+UszsalY61LuNHn650kkef/1Mcc7lQx6ukhfyvtfGYOEhEf2S4wv+gy0d6nZccHhvreYlX8cFZOAXzaT0ARdSTigMt7jBee6xygGTzsZ81HtnJlAY2lX19Or+PTZYeR6gHSr8MVKc18ali+aNJQq66V/er24/PVz66AQlS6GPLHwffkO5SaHAdu1lsHqGmADDvQl3DrX9q7w09DRTIKRsqDQAmHWCDiimDil7w/YT7+yZJNo+v4u9y5SUj5uOuIqhOOv05VvIBqJM2+HPffsDaayk1tB8egCcn/JtZ4mlAXf+sUT6MX4FlSNznMucrtsA0D4Qefp03PNCYvSPEw9EcpgSogp6HUXOW3t9n3U6sAhErHvi/VwXY2m7SEkxmSAogKZt7I1im4vFuZ6IiwRPpdsB5X4HdOp42TUETEJ0n2rqI4CCcBFHWY/JKkdOU+5C9+Gg12LR4phUVaPXZDopK5y2UikF8ID+w7sAmgvLAsprfKkxKZ6EElwxUlP3Op6ecz0O+TY9Yygv3XjBxcqK05j/2vlT9IVXPO2cM8EczYIe71Iak7mDBOYalICz0RJbsoTyUR5uoQMT5KLIavAqBR+X8jD+XaenG2Li4GU2nlysVbKgjQMSlm/luLnF2aInJuAR2fU7mxi99cRk=
deploy:
  provider: releases
  api_key:
    secure: ZyhfG3gZSeujvU0Lnl+uiFZEoGE8rCgMMu+cFG4uRa5JMUz0JqdDgK7z01Is83DsMIIzWvC+SiCEj+C6xvMVetErWEy0KeoNa9qOVcMZ6qvzSeMi7m2cz41mxi+uXwFFYyjG02x3Cvy4vJWYqbszHO/B8jWEwr/n3xU15Kl4MpKIJrnKPhW2QwuKjVcUzh4D0dqogiGiw/JfLtT2ld9FFdIfJ9GfXumpflYJcZf3iMZjrlMA7QthZEAowX2eLVNaU7MZ1/iY4ZVEgMpeEkuEAphARO6HlHg150iCFf9mK81S0NGJ6lSlCocJ9WBh5crX6Qn+9RNKlchr1tmgW9Sq37I+9GyOclnVp+SSEc9RIDo0lgesSc+oi/pv+I3533ezWs7qfSKL9bX47p4Tz6AwkIN0MOSKuu/xAkuQua1VvRMsbOwZOrnPzYi4ErA4mXPh2cix1EFgusL5E3FV7KPsU675Gl8tlHDb8iwtDuesGhngNHQbOZzZS9tOnSW0fWruDxx3wCgc1guV3l9DJC49rF7kK6lNDyHs16DvuwjaMMaxCcK8AEUsUGwLQdLZKP+XB/8QNW9k+wxJ9Bq3mbS/jnlVuAazPvW6ITgGxf1mJmj7wVMG+k/YVwzYd22n6DP1JrXMigJ51Ff//ylMG6cP54bU9EdI8JwT/XY3/IHJfbA=
  file: build/libs/xltv-rubocop-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xltv-rubocop-plugin
